name: teleport-cluster
apiVersion: v2
version: "9.3.18"
appVersion: "9.3.18"
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport

dependencies:
  - name: etcd
    version: 8.2.0
    condition: chartMode.custom
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 4.0.2
    condition: chartMode.custom
    repository: https://charts.min.io/