{{- if (eq .Values.chartMode "custom") -}}
  {{- $authentication := mustMergeOverwrite .Values.authentication (default dict .Values.authenticationSecondFactor) -}}
  {{- $logLevel := (coalesce .Values.logLevel .Values.log.level "INFO") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations.config }}
  annotations:
    {{- toYaml .Values.annotations.config | nindent 4 }}
  {{- end }}
data:
  teleport.yaml: |
  {{- if eq .Values.proxyListenerMode "multiplex" }}
    version: v2
  {{- end }}
    teleport:
      log:
        severity: {{ $logLevel }}
        output: {{ .Values.log.output }}
        format:
          output: {{ .Values.log.format }}
          extra_fields: {{ .Values.log.extraFields | toJson }}

      storage:
        type: etcd
        prefix: {{ .Values.custom.etcd.prefix | default "/teleport"}}
        username: {{ .Values.custom.etcd.username }}
        password_file: {{ .Values.custom.etcd.password_file | default "/etc/teleport-password" }}
        {{ if eq .Values.custom.etcd.insecure }}
        insecure: true
        {{ end }}
        audit_session_uri: {{ .Values.custom.audit.uri | quote }}

        data_dir: /var/lib/teleport

    auth_service:
      enabled: true
      cluster_name: {{ required "clusterName is required in chart values" .Values.clusterName }}
  {{- if .Values.enterprise }}
      license_file: '/var/lib/license/license.pem'
  {{- end }}
      authentication:
        type: "{{ required "authentication.type is required in chart values" (coalesce .Values.authenticationType $authentication.type) }}"
        local_auth: {{ $authentication.localAuth }}
  {{- if $authentication.connectorName }}
        connector_name: "{{ $authentication.connectorName }}"
  {{- end }}
  {{- if $authentication.lockingMode }}
        locking_mode: "{{ $authentication.lockingMode }}"
  {{- end }}
  {{- if $authentication.secondFactor }}
        second_factor: "{{ $authentication.secondFactor }}"
    {{- if not (or (eq $authentication.secondFactor "off") (eq $authentication.secondFactor "otp")) }}
        webauthn:
          rp_id: {{ required "clusterName is required in chart values" .Values.clusterName }}
      {{- if $authentication.webauthn }}
        {{- if $authentication.webauthn.attestationAllowedCas }}
          attestation_allowed_cas:
          {{- toYaml $authentication.webauthn.attestationAllowedCas | nindent 12 }}
        {{- end }}
        {{- if $authentication.webauthn.attestationDeniedCas }}
          attestation_denied_cas:
          {{- toYaml $authentication.webauthn.attestationDeniedCas | nindent 12 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.sessionRecording }}
      session_recording: {{ .Values.sessionRecording }}
  {{- end }}
  {{- if eq .Values.proxyListenerMode "multiplex" }}
      proxy_listener_mode: multiplex
  {{- end }}
  
    kubernetes_service:
      enabled: true
  {{- if eq .Values.proxyListenerMode "multiplex" }}
      listen_addr: 0.0.0.0:443
  {{- else if not .Values.proxyListenerMode }}
      listen_addr: 0.0.0.0:3027
  {{- end }}
  {{- if .Values.kubeClusterName }}
      kube_cluster_name: {{ .Values.kubeClusterName }}
  {{- else }}
      kube_cluster_name: {{ .Values.clusterName }}
  {{- end }}
  {{- if .Values.labels }}
      labels:
    {{- toYaml .Values.labels | nindent 8 }}
  {{- end }}

    proxy_service:
  {{- if .Values.publicAddr }}
      public_addr: {{- toYaml .Values.publicAddr | nindent 8 }}
  {{- else }}
      public_addr: '{{ required "clusterName is required in chart values" .Values.clusterName }}:443'
  {{- end }}
  {{- if .Values.sshPublicAddr }}
      ssh_public_addr: {{- toYaml .Values.sshPublicAddr | nindent 8 }}
  {{- end }}
  {{- if .Values.tunnelPublicAddr }}
      tunnel_public_addr: {{- toYaml .Values.tunnelPublicAddr | nindent 8 }}
  {{- end }}
  {{- if not .Values.proxyListenerMode }}
      kube_listen_addr: 0.0.0.0:3026
    {{- if .Values.kubePublicAddr }}
      kube_public_addr: {{- toYaml .Values.kubePublicAddr | nindent 8 }}
    {{- end }}
      mysql_listen_addr: 0.0.0.0:3036
    {{- if .Values.mysqlPublicAddr }}
      mysql_public_addr: {{- toYaml .Values.mysqlPublicAddr | nindent 8 }}
    {{- end }}
    {{- if .Values.separatePostgresListener }}
      postgres_listen_addr: 0.0.0.0:5432
      {{- if .Values.postgresPublicAddr }}
      postgres_public_addr: {{- toYaml .Values.postgresPublicAddr | nindent 8 }}
      {{- else }}
      postgres_public_addr: {{ .Values.clusterName }}:5432
      {{- end }}
    {{- end }}
    {{- if .Values.separateMongoListener }}
      mongo_listen_addr: 0.0.0.0:27017
      {{- if .Values.mongoPublicAddr }}
      mongo_public_addr: {{- toYaml .Values.mongoPublicAddr | nindent 8 }}
      {{- else }}
      mongo_public_addr: {{ .Values.clusterName }}:27017
      {{- end }}
    {{- end }}
  {{- end }}
      enabled: true
  {{- if or .Values.highAvailability.certManager.enabled .Values.tls.existingSecretName }}
      https_keypairs:
      - key_file: /etc/teleport-tls/tls.key
        cert_file: /etc/teleport-tls/tls.crt
  {{- else if .Values.acme }}
      acme:
        enabled: {{ .Values.acme }}
        email: {{ required "acmeEmail is required in chart values" .Values.acmeEmail }}
    {{- if .Values.acmeURI }}
        uri: {{ .Values.acmeURI }}
    {{- end }}
  {{- end }}
    ssh_service:
      enabled: false
{{- end -}}
